# Preprocessor
ADD_DEFINITIONS(/DO8_IS_WINDOWS=1)
ADD_DEFINITIONS(-DO8_IS_MINGW=1)

# Compiler        
SET (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -msse2 -Wall -Wl,-subsystem,windows")

IF(CMAKE_BUILD_TYPE MATCHES Debug)
	SET (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -ggdb")
ENDIF(CMAKE_BUILD_TYPE MATCHES Debug)